### ISSUE TITLE
Node becomes unusable

### ISSUE THREAD

**Issue by kaymcray** [rzllmr/node-editor#1]
A node becomes unusable after trying to attach a Link from Node A to Node B.
Node B gets multiple end points and after that is no longer usable.
Writing the body and the header is still possible.
Changing size is possible.
Moving the Node is still possible. But most of the time not. Not sure what triggers the node to be moveable again.
attacahing links from or to the faulty nodew is not possible
deliting the node is not possible.

Problem started while trying to attach a new link from Node A to Node B. In this process Node B turned faulty.

Attached file is the save.json for the bug
The faulty node in the example is "IP Table"
[Bug_.txt](https://github.com/rzllmr/node-editor/files/4176770/Bug_.txt)

**Comment by kaymcray** [comment]
After opening my own save the bug seems to be gone and the faulty node completly usable again...

**Comment by rzllmr** [comment]
Closed as outdated.
This cannot be reproduced with the latest version.
