### ISSUE TITLE
Marking multiple nodes and delete

### ISSUE THREAD

**Issue by kaymcray** [rzllmr/node-editor#3]
If marking multiple nodes at once and clicking delete. the application goes in a mode where you can click single nodes but no longer get feedback in form of the border highlighting.
and a single click immidiatley goes into moving mode. you'll be able to move the node arround until you clicked a second time.

**Comment by kaymcray** [comment]
But sometimes you can select multiple nodes and delete them without any issue.

**Comment by rzllmr** [comment]
Closed as outdated.
This cannot be reproduced with the latest version.
